[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Sarbani Kanjilal <>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "google-api-python-client>=2.160.0",
    "google-auth>=2.38.0",
    "google-auth-oauthlib>=1.2.1",
    "openai>=1.61.0",
]
